---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yml

  roles:
    - name: essentials
      tags: essentials

    - name: timezone
      tags: timezone

    - name: iptables
      tags: iptables
