---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yml

  roles:
    - name: essentials
      tags: essentials

    - name: timezone
      tags: timezone

    - name: iptables
      tags: iptables

    - name: fail2ban
      tags: fail2ban

    - name: kamaln7.swapfile
      tags: swapfile
      become: true

    - name: geerlingguy.nodejs
      tags: geerlingguy.nodejs
      become: true
