---

- hosts: all
  remote_user: "{{ user }}"

  vars_files:
    - vars/main.yml
    - vars/dirs.yml

  roles:
    - name: essentials
      tags: essentials

    - name: timezone
      tags: timezone

    - name: iptables
      tags: iptables

    - name: fail2ban
      tags: fail2ban

    - name: kamaln7.swapfile
      tags: swapfile
      become: true

    - name: certbot
      tags: ssl

    - name: ssl
      tags: ssl

    - name: geerlingguy.nodejs
      tags: nodejs
      become: true

    - name: nginx
      tags: nginx
      become: true

    - name: php
      tags: php
      become: true

    - name: geerlingguy.composer
      tags: composer
      become: true

    - name: geerlingguy.mysql
      tags: mysql
      become: true

  tasks:
    - name: Create base directory
      file:
        path: "{{ domain_path }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0711
      become: true

    - name: Create releases directory
      file:
        path: "{{ releases_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0711
      become: true

    - name: Create persistent directory
      file:
        path: "{{ persistent_dir }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0711
      become: true

    - name: Copy storage
      copy:
        src: storage
        dest: "{{ persistent_dir }}/"
      become: true

    - include: tasks/set_owner_and_group.yml
      vars:
        dir_to_chown: "{{ persistent_dir }}/storage"

    - include: tasks/check_that_folder_is_writable.yml
      vars:
        dir_to_check: "{{ persistent_dir }}/storage"
