---

- name: Get current build number
  local_action: shell date +%Y-%m-%d-%H-%M-%S
  register: current_time
  run_once: true

- name: Register release variables
  set_fact:
    new_release_name: "{{ current_time.stdout }}"
    new_release_dir: "{{ releases_dir }}/{{ current_time.stdout }}"
